[package]
name = "bevy_labeled_asset_conflict"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
ron = "0.8"
serde = { version = "1", features = ["derive"] }

[[example]]
name = "conflict"
path = "examples/conflict.rs"

[[example]]
name = "fine"
path = "examples/fine.rs"